// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	model "github.com/matbarofex/mtz-crypto/pkg/model"
	mock "github.com/stretchr/testify/mock"
)

// MarketDataService is an autogenerated mock type for the MarketDataService type
type MarketDataService struct {
	mock.Mock
}

// ConsumeMD provides a mock function with given fields: mdChannel
func (_m *MarketDataService) ConsumeMD(mdChannel model.MdChannel) {
	_m.Called(mdChannel)
}

// GetMD provides a mock function with given fields: symbol
func (_m *MarketDataService) GetMD(symbol string) (model.MarketData, error) {
	ret := _m.Called(symbol)

	var r0 model.MarketData
	if rf, ok := ret.Get(0).(func(string) model.MarketData); ok {
		r0 = rf(symbol)
	} else {
		r0 = ret.Get(0).(model.MarketData)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(symbol)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
