// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	model "github.com/matbarofex/mtz-crypto/pkg/model"
	mock "github.com/stretchr/testify/mock"
)

// MarketDataStore is an autogenerated mock type for the MarketDataStore type
type MarketDataStore struct {
	mock.Mock
}

// GetMD provides a mock function with given fields: symbol
func (_m *MarketDataStore) GetMD(symbol string) (model.MarketData, error) {
	ret := _m.Called(symbol)

	var r0 model.MarketData
	if rf, ok := ret.Get(0).(func(string) model.MarketData); ok {
		r0 = rf(symbol)
	} else {
		r0 = ret.Get(0).(model.MarketData)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(symbol)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetOrUpdateMD provides a mock function with given fields: md
func (_m *MarketDataStore) SetOrUpdateMD(md model.MarketData) error {
	ret := _m.Called(md)

	var r0 error
	if rf, ok := ret.Get(0).(func(model.MarketData) error); ok {
		r0 = rf(md)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
