// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// WalletController is an autogenerated mock type for the WalletController type
type WalletController struct {
	mock.Mock
}

// GetWalletValue provides a mock function with given fields: ctx
func (_m *WalletController) GetWalletValue(ctx *gin.Context) {
	_m.Called(ctx)
}
