// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	model "github.com/matbarofex/mtz-crypto/pkg/model"
	mock "github.com/stretchr/testify/mock"
)

// WalletService is an autogenerated mock type for the WalletService type
type WalletService struct {
	mock.Mock
}

// GetWalletValue provides a mock function with given fields: req
func (_m *WalletService) GetWalletValue(req model.GetWalletValueRequest) (model.GetWalletValueResponse, error) {
	ret := _m.Called(req)

	var r0 model.GetWalletValueResponse
	if rf, ok := ret.Get(0).(func(model.GetWalletValueRequest) model.GetWalletValueResponse); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Get(0).(model.GetWalletValueResponse)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(model.GetWalletValueRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
