// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	model "github.com/matbarofex/mtz-crypto/pkg/model"
	mock "github.com/stretchr/testify/mock"
)

// WalletStore is an autogenerated mock type for the WalletStore type
type WalletStore struct {
	mock.Mock
}

// GetWallet provides a mock function with given fields: id
func (_m *WalletStore) GetWallet(id string) (model.Wallet, error) {
	ret := _m.Called(id)

	var r0 model.Wallet
	if rf, ok := ret.Get(0).(func(string) model.Wallet); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(model.Wallet)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
